# Copyright (C) 2026 Ascensio System SIA
import json
import os
import socket

from odoo.tests import tagged
from odoo.tests.common import HttpCase

from odoo.addons.onlyoffice_odoo.utils import config_utils

DOCSERVER_URL = os.environ.get("ONLYOFFICE_TEST_DOCSERVER_URL", "http://documentserver/")
MODEL_NAME = "hr.employee"


@tagged("post_install", "-at_install", "-standard", "external_docserver")
class TestOnlyofficeTemplatesDocumentServer(HttpCase):
    """Prints a template through a real Document Server (see test_models.py for the mocked version).

    Only runs when ONLYOFFICE_TEST_LIVE_DOCSERVER is set (see tests/__init__.py).

    The "-standard" tag is required so Odoo's BaseCase does not patch
    requests.Session.send to block external HTTP calls: this test
    deliberately hits a real Document Server over the network.
    """

    @classmethod
    def setUpClass(cls):
        super().setUpClass()
        cls.ir_model = cls.env["ir.model"].search([("model", "=", MODEL_NAME)], limit=1)
        if not cls.ir_model:
            return

        cls.demo_record = cls.env[MODEL_NAME].search([], limit=1)
        if not cls.demo_record:
            cls.demo_record = cls.env[MODEL_NAME].create({"name": "ONLYOFFICE Test Employee"})

        cls.http_user = (
            cls.env["res.users"]
            .sudo()
            .create(
                {
                    "name": "OO Docserver Test User",
                    "login": "_oo_docserver_test",
                    "password": "_oo_test_pass_123",
                    "groups_id": [(6, 0, [cls.env.ref("base.group_user").id, cls.env.ref("base.group_system").id])],
                }
            )
        )

        config_utils.set_doc_server_public_url(cls.env, DOCSERVER_URL)
        config_utils.set_doc_server_inner_url(cls.env, DOCSERVER_URL)
        config_utils.set_jwt_secret(cls.env, "")

        # Document Server must call this Odoo instance back, so use the
        # container's real IP instead of 'localhost' from base_url().
        container_ip = socket.gethostbyname(socket.gethostname())
        port = cls.base_url().rsplit(":", 1)[-1]
        config_utils.set_doc_server_odoo_url(cls.env, f"http://{container_ip}:{port}/")

    def setUp(self):
        super().setUp()
        if not self.ir_model:
            self.skipTest(f"Model {MODEL_NAME} is not installed in this test environment")

    def test_print_demo_record_with_real_document_server(self):
        """Printing a demo record through an onlyoffice-pdf report must
        return a real, filled PDF generated by the Document Server."""
        demo = self.env["onlyoffice.odoo.demo.templates"].create({})
        data = demo.get_template_data()
        # "path" is already relative to the templates dir and includes the
        # model subfolder (e.g. "hr.employee/Employee.pdf"), matching what
        # the frontend widget sends in `selected_templates`.
        template_path = data["structure"][MODEL_NAME]["files"][0]["path"]
        demo.selected_templates = json.dumps([template_path])
        demo.action_save()

        template = self.env["onlyoffice.odoo.templates"].search([("template_model_model", "=", MODEL_NAME)], limit=1)
        template.create_action()
        report = template.report_id

        self.authenticate("_oo_docserver_test", "_oo_test_pass_123")
        response = self.url_open(f"/report/onlyoffice-pdf/{report.report_name}/{self.demo_record.id}")

        self.assertEqual(response.status_code, 200)
        self.assertEqual(response.headers.get("Content-Type"), "application/pdf")
        self.assertTrue(response.content.startswith(b"%PDF"))
